from pysubparser import parser

def convert_srt_to_ass(srt_file, ass_file):
    subs = parser.parse(srt_file)

    ass_header = """[Script Info]
; Script generated by SRT to ASS Converter
Title: Lyrics Video Subtitles
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H0000FFFF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,3,1,2,10,10,30,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    with open(ass_file, 'w', encoding='utf-8') as file:
        file.write(ass_header)

        for sub in subs:
            # Format start and end timecodes as HH:MM:SS.MS (correcting the timestamp format)
            start = str(sub.start).split(".")[0]  + ".0"  # Correct format with period
            end = str(sub.end).split(".")[0] + ".0"  # Correct format with period
            text = sub.text.replace("\n", "\\N")  # Handle multi-line text

            # Write the subtitle line in .ass format
            file.write(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{{\\fad(300,300)}}{text}\n")

# Example usage
convert_srt_to_ass("test.mp4.srt", "output.ass")
