import os
from config import Config

class AdvancedSRTtoASSConverter:
    def __init__(self, config: Config):
        """Initialize with video frame dimensions for adaptive subtitles."""
        self.config = config
        self.word_threshold = 0.1  # Time (s) below which words will merge

    def _generate_ass_header(self):
        """Generates ASS header with video resolution for proper scaling."""
        return f"""[Script Info]
    ; Script generated by Liri.ai - your music-friendly bot
    Title: Word-Level Animated Subtitles
    ScriptType: v4.00+
    Collisions: Normal
    PlayResX: {self.config.video_resolution[0]}  ;
    PlayResY: {self.config.video_resolution[1]} ;
    PlayDepth: 0

    [V4+ Styles]
    Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
    Style: Default,Default,{self._calculate_font_size()},&H00FFFFFF,&H0000FFFF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,4,1,5,20,20,40,1

    [Events]
    Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
    """


    def convert(self, subs, ass_file_name, task_config: Config):
        """Converts an SRT file with word-level timestamps to an animated ASS subtitle file."""
        frame_width, frame_height = task_config.video_resolution
        frame_width, frame_height = (int(frame_width), int(frame_height))
        
        subs = self._group_fast_words(subs)
        
        with open(ass_file_name, 'w', encoding='utf-8') as file:
            file.write(self._generate_ass_header())

            for i, sub in enumerate(subs):
                time_start = sub['start']
                time_end = sub['end']
                duration = time_end - time_start
                text = sub['word']
                start = self._format_time(time_start)
                end = self._format_time(time_end)

                font_size = self._calculate_font_size()
                pos_offset = -1 if i%2 ==0 else 1
                pos_x_still = 0 if i%3==0 else 1
                pos_x = frame_width // 2
                pos_x_new = pos_x + (pos_offset * pos_x_still* int(frame_width*0.01))# Slight horizontal shift
                pos_y = frame_height // 2 # Centered text with gradual stacking
                pos_y_still = 0 if i%3!=0 else 1
                pos_y_new = pos_x + (pos_offset * pos_y_still * int(frame_height*0.01))# Slight horizontal shift

                # **Advanced Effects**
                final_font_size = font_size * (max(duration, 0.75) if duration < 1 else min(duration, 1.25))
                effects = ("{"+
                    f"\move({pos_x},{pos_y},{pos_x},{pos_y},0,{int(duration*1000)})\\fs{font_size}\\bord2\\shad1\\1c&HFFFFFF&\\t(0,{int(duration*1000)},\\fs{final_font_size})"
                    + "}"
                )
        
                file.write(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{effects}{text}\n")
                

        print(f"Lyrics saved to {ass_file_name}")
        return ass_file_name

    def _group_fast_words(self, words:list):
        """Groups words if they appear too fast (threshold < self.word_threshold)."""
        return words
        reversed_words = [_.copy() for _ in words]
        new_words = []
        for i, sub in enumerate(reversed_words):
            time_start = sub['start']
            time_end = sub['end']
            duration = time_start - new_words[-1]['end'] if i != 0 else 0
            text = sub['word']
            if i == 0 or duration > self.word_threshold:
                new_words.append(sub)
            else:
                new_words[-1]['end'] = time_end
                new_words[-1]['word'] += ' ' + text
        return new_words

    def _format_time(self, seconds):
        """Formats time in HH:MM:SS.ms format for ASS subtitles."""
        h = int(seconds // 3600)
        m = int((seconds % 3600) // 60)
        s = int(seconds % 60)
        ms = int((seconds - int(seconds)) * 100)
        return f"{h:01d}:{m:02d}:{s:02d}.{ms:02d}"

    def _calculate_font_size(self):
        """Calculates a dynamic font size based on video resolution."""
        frame_width, frame_height = self.config.video_resolution
        return int((frame_width) * 0.2)

if __name__ == "__main__":
    # Example Usage
    config = Config('./', './')
    config.video_resolution = (1920, 1080)
    converter = AdvancedSRTtoASSConverter(config)
    converter.convert("input.srt", "output.ass")
